kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/part-of: {{ .Release.Name }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.PrivateContainerRegistry }}{{ .Release.Name }}-backend:latest
          env:
            - name: ASPNETCORE_URLS
              value: http://*:5050
            - name: ASPNETCORE_ENVIRONMENT
              value: 'Production'
            - name: CONNECTIONSTRING_POSTGRES
              value: 'Server=postgres;Port={{ .Values.PostgresPort }};User Id={{ .Values.PostgresUserId }};Password={{ .Values.PostgresPassword }};'
          ports:
            - containerPort: 5050
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: backend
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.BackendServicePort }}
      targetPort: 5050