kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: {{ .Release.Name }}
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.PostgresPassword }}
          ports:
            - containerPort: {{ .Values.PostgresPort }}
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: postgres
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.PostgresPort }}
      targetPort: {{ .Values.PostgresPort }}