// <auto-generated />
using System;
using Dnw.Weather.Tye.Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dnw.Weather.Tye.Backend.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20221128112822_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 11, 29, 11, 28, 22, 60, DateTimeKind.Utc).AddTicks(5010),
                            Summary = "Warm",
                            TemperatureC = 37
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 11, 30, 11, 28, 22, 60, DateTimeKind.Utc).AddTicks(5030),
                            Summary = "Sweltering",
                            TemperatureC = -5
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 12, 1, 11, 28, 22, 60, DateTimeKind.Utc).AddTicks(5030),
                            Summary = "Balmy",
                            TemperatureC = -2
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 12, 2, 11, 28, 22, 60, DateTimeKind.Utc).AddTicks(5040),
                            Summary = "Freezing",
                            TemperatureC = 0
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 12, 3, 11, 28, 22, 60, DateTimeKind.Utc).AddTicks(5040),
                            Summary = "Mild",
                            TemperatureC = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
